name: str_erp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  
  # Firebase
  firebase_core: ^3.13.0  # Base firebase version
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.3.6  # Updated to match easy_storage requirement
  firebase_app_check: ^0.3.2+5
  
  # Location & Maps
  geolocator: ^14.0.0
  google_maps_flutter: ^2.5.3
  
  # Files & Storage
  path_provider: ^2.1.2
  easy_storage: ^0.0.21
  permission_handler: ^12.0.0+1
  file_picker: ^8.3.7
  excel: ^4.0.2
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  
  # Media
  image_picker: ^1.0.7

  package_info_plus: ^8.3.0
  
  # Background Processing
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  # workmanager: ^0.5.2  # Still commenting out temporarily
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^19.1.0
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1

  #map
  flutter_map: ^8.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true