// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ZIau0Xe81HRLi75eEfkgqQbceOAknGU',
    appId: '1:520030226703:web:1fe8726936c0e9234b967a',
    messagingSenderId: '520030226703',
    projectId: 'strerp-6c7fb',
    authDomain: 'strerp-6c7fb.firebaseapp.com',
    storageBucket: 'strerp-6c7fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsZs1U896Uqps9StDJ_da-Dh6M7SVwFg',
    appId: '1:520030226703:android:9608a4ee1c52a8364b967a',
    messagingSenderId: '520030226703',
    projectId: 'strerp-6c7fb',
    storageBucket: 'strerp-6c7fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUgDobRwy29ll82W0eVoWotjLLZxnJtQ',
    appId: '1:520030226703:ios:6102e58dfb1bd0cd4b967a',
    messagingSenderId: '520030226703',
    projectId: 'strerp-6c7fb',
    storageBucket: 'strerp-6c7fb.firebasestorage.app',
    iosBundleId: 'com.example.strErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALUgDobRwy29ll82W0eVoWotjLLZxnJtQ',
    appId: '1:520030226703:ios:6102e58dfb1bd0cd4b967a',
    messagingSenderId: '520030226703',
    projectId: 'strerp-6c7fb',
    storageBucket: 'strerp-6c7fb.firebasestorage.app',
    iosBundleId: 'com.example.strErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_QKE0T9iecR-FRBGJ5nvHaKQVwny19g',
    appId: '1:520030226703:web:1b425a870224dc744b967a',
    messagingSenderId: '520030226703',
    projectId: 'strerp-6c7fb',
    authDomain: 'strerp-6c7fb.firebaseapp.com',
    storageBucket: 'strerp-6c7fb.firebasestorage.app',
  );

}